In [2]:
# Import required libraries

import json
import pandas as pd

In [3]:
# Read JSON file

with open("web_feedback.json", "r") as file:
    feedback_data = json.load(file)

# Display JSON data
feedback_data

[{'customer_id': 1, 'rating': 5, 'comments': 'Excellent service!'},
 {'customer_id': 2, 'rating': 4, 'comments': 'Good experience overall.'},
 {'customer_id': 3, 'rating': 2, 'comments': 'Late delivery.'}]

In [4]:
# Convert JSON data into a DataFrame

feedback_df = pd.DataFrame(feedback_data)

# Display DataFrame
feedback_df

   customer_id  rating                  comments
0            1       5        Excellent service!
1            2       4  Good experience overall.
2            3       2            Late delivery.

In [5]:
# Check for missing values in JSON data

feedback_df.isnull().sum()

customer_id    0
rating         0
comments       0
dtype: int64

In [6]:
# Validate rating values in JSON data

invalid_ratings = feedback_df[
    (feedback_df["rating"] < 1) |
    (feedback_df["rating"] > 5)
]

invalid_ratings

Empty DataFrame
Columns: [customer_id, rating, comments]
Index: []

In [7]:
# Check for duplicate records in JSON data

duplicate_records = feedback_df[
    feedback_df.duplicated()
]

duplicate_records

Empty DataFrame
Columns: [customer_id, rating, comments]
Index: []

In [8]:
# Add review date column to JSON data

feedback_df["review_date"] = "2024-01-01"

# Display updated DataFrame
feedback_df

   customer_id  rating                  comments review_date
0            1       5        Excellent service!  2024-01-01
1            2       4  Good experience overall.  2024-01-01
2            3       2            Late delivery.  2024-01-01

In [9]:
# Import MySQL connector

import mysql.connector

# Connect to MySQL database

connection = mysql.connector.connect(
    host="localhost",
    user="root",
    password="55003698",
    database="etl_final_project"
)

# Create cursor object

cursor = connection.cursor()

print("Connected to MySQL successfully!")

Connected to MySQL successfully!

In [10]:
# Insert JSON data into web_feedback_staging table

insert_query = """
INSERT INTO web_feedback_staging
(customer_id, rating, comments, review_date)
VALUES (%s, %s, %s, %s)
"""

# Insert rows into table

for index, row in feedback_df.iterrows():
    cursor.execute(insert_query, (
        row["customer_id"],
        row["rating"],
        row["comments"],
        row["review_date"]
    ))

# Commit changes

connection.commit()

print("JSON data inserted successfully!")

JSON data inserted successfully!